<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Weft.Client.Native</AssemblyName>
    <RootNamespace>Weft.Client.Native</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <NativeLib>Shared</NativeLib>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Weft.Client.Core/Weft.Client.Core.csproj" />
  </ItemGroup>
</Project>
